package com.students.mapper;

import com.students.bean.Studentsinfo;
import com.students.bean.StudentsinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentsinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int countByExample(StudentsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int deleteByExample(StudentsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int deleteByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int insert(Studentsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int insertSelective(Studentsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    List<Studentsinfo> selectByExample(StudentsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    Studentsinfo selectByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Studentsinfo record, @Param("example") StudentsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int updateByExample(@Param("record") Studentsinfo record, @Param("example") StudentsinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int updateByPrimaryKeySelective(Studentsinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsinfo
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    int updateByPrimaryKey(Studentsinfo record);
}