package com.students.mapper;

import com.students.bean.Studentspass;
import com.students.bean.StudentspassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentspassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int countByExample(StudentspassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int deleteByExample(StudentspassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int deleteByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int insert(Studentspass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int insertSelective(Studentspass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    List<Studentspass> selectByExample(StudentspassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    Studentspass selectByPrimaryKey(String stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") Studentspass record, @Param("example") StudentspassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int updateByExample(@Param("record") Studentspass record, @Param("example") StudentspassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int updateByPrimaryKeySelective(Studentspass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentspass
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    int updateByPrimaryKey(Studentspass record);
}