package com.students.mapper;

import com.students.bean.Studentsorg;
import com.students.bean.StudentsorgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentsorgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int countByExample(StudentsorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int deleteByExample(StudentsorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int deleteByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int insert(Studentsorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int insertSelective(Studentsorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    List<Studentsorg> selectByExample(StudentsorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    Studentsorg selectByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Studentsorg record, @Param("example") StudentsorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int updateByExample(@Param("record") Studentsorg record, @Param("example") StudentsorgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int updateByPrimaryKeySelective(Studentsorg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsorg
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    int updateByPrimaryKey(Studentsorg record);
}