package com.students.mapper;

import com.students.bean.Studentsprize;
import com.students.bean.StudentsprizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentsprizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int countByExample(StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int deleteByExample(StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int deleteByPrimaryKey(Integer prizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int insert(Studentsprize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int insertSelective(Studentsprize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    List<Studentsprize> selectByExampleWithBLOBs(StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    List<Studentsprize> selectByExample(StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    Studentsprize selectByPrimaryKey(Integer prizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Studentsprize record, @Param("example") StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Studentsprize record, @Param("example") StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int updateByExample(@Param("record") Studentsprize record, @Param("example") StudentsprizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int updateByPrimaryKeySelective(Studentsprize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Studentsprize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentsprize
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    int updateByPrimaryKey(Studentsprize record);
}