package com.students.bean;

public class Grade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.STU_ID
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.STU_NAME
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.AVG_PONIT
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    private Float avgPonit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.AVR_GRADE
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    private Integer avrGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade.AVR_RANK
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    private String avrRank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.STU_ID
     *
     * @return the value of grade.STU_ID
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.STU_ID
     *
     * @param stuId the value for grade.STU_ID
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.STU_NAME
     *
     * @return the value of grade.STU_NAME
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.STU_NAME
     *
     * @param stuName the value for grade.STU_NAME
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.AVG_PONIT
     *
     * @return the value of grade.AVG_PONIT
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public Float getAvgPonit() {
        return avgPonit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.AVG_PONIT
     *
     * @param avgPonit the value for grade.AVG_PONIT
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public void setAvgPonit(Float avgPonit) {
        this.avgPonit = avgPonit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.AVR_GRADE
     *
     * @return the value of grade.AVR_GRADE
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public Integer getAvrGrade() {
        return avrGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.AVR_GRADE
     *
     * @param avrGrade the value for grade.AVR_GRADE
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public void setAvrGrade(Integer avrGrade) {
        this.avrGrade = avrGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade.AVR_RANK
     *
     * @return the value of grade.AVR_RANK
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public String getAvrRank() {
        return avrRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade.AVR_RANK
     *
     * @param avrRank the value for grade.AVR_RANK
     *
     * @mbggenerated Tue Mar 13 20:48:35 CST 2018
     */
    public void setAvrRank(String avrRank) {
        this.avrRank = avrRank == null ? null : avrRank.trim();
    }

	@Override
	public String toString() {
		return "Grade [stuId=" + stuId + ", stuName=" + stuName + ", avgPonit=" + avgPonit + ", avrGrade=" + avrGrade
				+ ", avrRank=" + avrRank + "]";
	}
    
	public void init() {
		System.out.println("1111111111111111155555555555555555111515_________-");
		System.out.println("1111111111111111155555555555555555111515_________-");
	}
    
}