package com.students.bean;

public class Resume {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.STU_ID
     *
     * @mbggenerated Sat Nov 24 15:04:35 CST 2018
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.RESUME_FILE
     *
     * @mbggenerated Sat Nov 24 15:04:35 CST 2018
     */
    private String resumeFile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.STU_ID
     *
     * @return the value of resume.STU_ID
     *
     * @mbggenerated Sat Nov 24 15:04:35 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.STU_ID
     *
     * @param stuId the value for resume.STU_ID
     *
     * @mbggenerated Sat Nov 24 15:04:35 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.RESUME_FILE
     *
     * @return the value of resume.RESUME_FILE
     *
     * @mbggenerated Sat Nov 24 15:04:35 CST 2018
     */
    public String getResumeFile() {
        return resumeFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.RESUME_FILE
     *
     * @param resumeFile the value for resume.RESUME_FILE
     *
     * @mbggenerated Sat Nov 24 15:04:35 CST 2018
     */
    public void setResumeFile(String resumeFile) {
        this.resumeFile = resumeFile == null ? null : resumeFile.trim();
    }
}