package com.students.bean;

public class Studentsinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_ID
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_NAME
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_GENDER
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_AGE
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private Integer stuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.IDENTITY
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_CLASS
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_MAJOR
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_DORM
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuDorm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_QQ
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_TEL
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_STATUS
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_HOME
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_INTRO
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsinfo.STU_GRADE
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    private String stuGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_ID
     *
     * @return the value of studentsinfo.STU_ID
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_ID
     *
     * @param stuId the value for studentsinfo.STU_ID
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_NAME
     *
     * @return the value of studentsinfo.STU_NAME
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_NAME
     *
     * @param stuName the value for studentsinfo.STU_NAME
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_GENDER
     *
     * @return the value of studentsinfo.STU_GENDER
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_GENDER
     *
     * @param stuGender the value for studentsinfo.STU_GENDER
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_AGE
     *
     * @return the value of studentsinfo.STU_AGE
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_AGE
     *
     * @param stuAge the value for studentsinfo.STU_AGE
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.IDENTITY
     *
     * @return the value of studentsinfo.IDENTITY
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.IDENTITY
     *
     * @param identity the value for studentsinfo.IDENTITY
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_CLASS
     *
     * @return the value of studentsinfo.STU_CLASS
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuClass() {
        return stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_CLASS
     *
     * @param stuClass the value for studentsinfo.STU_CLASS
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuClass(String stuClass) {
        this.stuClass = stuClass == null ? null : stuClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_MAJOR
     *
     * @return the value of studentsinfo.STU_MAJOR
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_MAJOR
     *
     * @param stuMajor the value for studentsinfo.STU_MAJOR
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_DORM
     *
     * @return the value of studentsinfo.STU_DORM
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuDorm() {
        return stuDorm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_DORM
     *
     * @param stuDorm the value for studentsinfo.STU_DORM
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuDorm(String stuDorm) {
        this.stuDorm = stuDorm == null ? null : stuDorm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_QQ
     *
     * @return the value of studentsinfo.STU_QQ
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuQq() {
        return stuQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_QQ
     *
     * @param stuQq the value for studentsinfo.STU_QQ
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuQq(String stuQq) {
        this.stuQq = stuQq == null ? null : stuQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_TEL
     *
     * @return the value of studentsinfo.STU_TEL
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuTel() {
        return stuTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_TEL
     *
     * @param stuTel the value for studentsinfo.STU_TEL
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuTel(String stuTel) {
        this.stuTel = stuTel == null ? null : stuTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_STATUS
     *
     * @return the value of studentsinfo.STU_STATUS
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuStatus() {
        return stuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_STATUS
     *
     * @param stuStatus the value for studentsinfo.STU_STATUS
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuStatus(String stuStatus) {
        this.stuStatus = stuStatus == null ? null : stuStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_HOME
     *
     * @return the value of studentsinfo.STU_HOME
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuHome() {
        return stuHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_HOME
     *
     * @param stuHome the value for studentsinfo.STU_HOME
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuHome(String stuHome) {
        this.stuHome = stuHome == null ? null : stuHome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_INTRO
     *
     * @return the value of studentsinfo.STU_INTRO
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuIntro() {
        return stuIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_INTRO
     *
     * @param stuIntro the value for studentsinfo.STU_INTRO
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuIntro(String stuIntro) {
        this.stuIntro = stuIntro == null ? null : stuIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsinfo.STU_GRADE
     *
     * @return the value of studentsinfo.STU_GRADE
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public String getStuGrade() {
        return stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsinfo.STU_GRADE
     *
     * @param stuGrade the value for studentsinfo.STU_GRADE
     *
     * @mbggenerated Sat Nov 24 15:07:48 CST 2018
     */
    public void setStuGrade(String stuGrade) {
        this.stuGrade = stuGrade == null ? null : stuGrade.trim();
    }
}