package com.students.bean;

import java.util.Date;

public class Studentsorg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_ID
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.STU_ID
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_NAME
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_DUTY
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String orgDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_BEGIN
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private Date orgBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_END
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private Date orgEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_HONOR
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String orgHonor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_INTRO
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String orgIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_CLASS
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String orgClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.STU_NAME
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsorg.ORG_TYPE
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    private String orgType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_ID
     *
     * @return the value of studentsorg.ORG_ID
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_ID
     *
     * @param orgId the value for studentsorg.ORG_ID
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.STU_ID
     *
     * @return the value of studentsorg.STU_ID
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.STU_ID
     *
     * @param stuId the value for studentsorg.STU_ID
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_NAME
     *
     * @return the value of studentsorg.ORG_NAME
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_NAME
     *
     * @param orgName the value for studentsorg.ORG_NAME
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_DUTY
     *
     * @return the value of studentsorg.ORG_DUTY
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getOrgDuty() {
        return orgDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_DUTY
     *
     * @param orgDuty the value for studentsorg.ORG_DUTY
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgDuty(String orgDuty) {
        this.orgDuty = orgDuty == null ? null : orgDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_BEGIN
     *
     * @return the value of studentsorg.ORG_BEGIN
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public Date getOrgBegin() {
        return orgBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_BEGIN
     *
     * @param orgBegin the value for studentsorg.ORG_BEGIN
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgBegin(Date orgBegin) {
        this.orgBegin = orgBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_END
     *
     * @return the value of studentsorg.ORG_END
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public Date getOrgEnd() {
        return orgEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_END
     *
     * @param orgEnd the value for studentsorg.ORG_END
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgEnd(Date orgEnd) {
        this.orgEnd = orgEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_HONOR
     *
     * @return the value of studentsorg.ORG_HONOR
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getOrgHonor() {
        return orgHonor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_HONOR
     *
     * @param orgHonor the value for studentsorg.ORG_HONOR
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgHonor(String orgHonor) {
        this.orgHonor = orgHonor == null ? null : orgHonor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_INTRO
     *
     * @return the value of studentsorg.ORG_INTRO
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getOrgIntro() {
        return orgIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_INTRO
     *
     * @param orgIntro the value for studentsorg.ORG_INTRO
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgIntro(String orgIntro) {
        this.orgIntro = orgIntro == null ? null : orgIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_CLASS
     *
     * @return the value of studentsorg.ORG_CLASS
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getOrgClass() {
        return orgClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_CLASS
     *
     * @param orgClass the value for studentsorg.ORG_CLASS
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgClass(String orgClass) {
        this.orgClass = orgClass == null ? null : orgClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.STU_NAME
     *
     * @return the value of studentsorg.STU_NAME
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.STU_NAME
     *
     * @param stuName the value for studentsorg.STU_NAME
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsorg.ORG_TYPE
     *
     * @return the value of studentsorg.ORG_TYPE
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsorg.ORG_TYPE
     *
     * @param orgType the value for studentsorg.ORG_TYPE
     *
     * @mbggenerated Wed Sep 12 11:50:05 CST 2018
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType == null ? null : orgType.trim();
    }
}