package com.students.bean;

import java.util.Date;

import javax.validation.constraints.Pattern;

public class Studentsprize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_ID
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private Integer prizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.STU_ID
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.STU_NAME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_NAME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_DATE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    @Pattern(regexp="yyyy-MM-dd hh:mm:ss")
    private Date prizeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_CLASS
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String prizeClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_LEVEL
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String prizeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_FILE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String prizeFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.STATUS
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.SUBMIT_DATE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    @Pattern(regexp="yyyy-MM-dd hh:mm:ss")
    private Date submitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.reason
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.CHECK_TIME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    @Pattern(regexp="yyyy-MM-dd hh:mm:ss")
    private Date checkTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentsprize.PRIZE_INTRO
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    private String prizeIntro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_ID
     *
     * @return the value of studentsprize.PRIZE_ID
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public Integer getPrizeId() {
        return prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_ID
     *
     * @param prizeId the value for studentsprize.PRIZE_ID
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeId(Integer prizeId) {
        this.prizeId = prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.STU_ID
     *
     * @return the value of studentsprize.STU_ID
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.STU_ID
     *
     * @param stuId the value for studentsprize.STU_ID
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.STU_NAME
     *
     * @return the value of studentsprize.STU_NAME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.STU_NAME
     *
     * @param stuName the value for studentsprize.STU_NAME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_NAME
     *
     * @return the value of studentsprize.PRIZE_NAME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_NAME
     *
     * @param prizeName the value for studentsprize.PRIZE_NAME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName == null ? null : prizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_DATE
     *
     * @return the value of studentsprize.PRIZE_DATE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public Date getPrizeDate() {
        return prizeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_DATE
     *
     * @param prizeDate the value for studentsprize.PRIZE_DATE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeDate(Date prizeDate) {
        this.prizeDate = prizeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_CLASS
     *
     * @return the value of studentsprize.PRIZE_CLASS
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getPrizeClass() {
        return prizeClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_CLASS
     *
     * @param prizeClass the value for studentsprize.PRIZE_CLASS
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeClass(String prizeClass) {
        this.prizeClass = prizeClass == null ? null : prizeClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_LEVEL
     *
     * @return the value of studentsprize.PRIZE_LEVEL
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getPrizeLevel() {
        return prizeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_LEVEL
     *
     * @param prizeLevel the value for studentsprize.PRIZE_LEVEL
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeLevel(String prizeLevel) {
        this.prizeLevel = prizeLevel == null ? null : prizeLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_FILE
     *
     * @return the value of studentsprize.PRIZE_FILE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getPrizeFile() {
        return prizeFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_FILE
     *
     * @param prizeFile the value for studentsprize.PRIZE_FILE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeFile(String prizeFile) {
        this.prizeFile = prizeFile == null ? null : prizeFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.STATUS
     *
     * @return the value of studentsprize.STATUS
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.STATUS
     *
     * @param status the value for studentsprize.STATUS
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.SUBMIT_DATE
     *
     * @return the value of studentsprize.SUBMIT_DATE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.SUBMIT_DATE
     *
     * @param submitDate the value for studentsprize.SUBMIT_DATE
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.reason
     *
     * @return the value of studentsprize.reason
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.reason
     *
     * @param reason the value for studentsprize.reason
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.CHECK_TIME
     *
     * @return the value of studentsprize.CHECK_TIME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.CHECK_TIME
     *
     * @param checkTime the value for studentsprize.CHECK_TIME
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentsprize.PRIZE_INTRO
     *
     * @return the value of studentsprize.PRIZE_INTRO
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public String getPrizeIntro() {
        return prizeIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentsprize.PRIZE_INTRO
     *
     * @param prizeIntro the value for studentsprize.PRIZE_INTRO
     *
     * @mbggenerated Mon Jun 11 11:38:22 CST 2018
     */
    public void setPrizeIntro(String prizeIntro) {
        this.prizeIntro = prizeIntro == null ? null : prizeIntro.trim();
    }
}