package com.students.bean;

public class Studentspass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentspass.STU_ID
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentspass.STU_PSW
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    private String stuPsw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentspass.STU_ID
     *
     * @return the value of studentspass.STU_ID
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentspass.STU_ID
     *
     * @param stuId the value for studentspass.STU_ID
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentspass.STU_PSW
     *
     * @return the value of studentspass.STU_PSW
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    public String getStuPsw() {
        return stuPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentspass.STU_PSW
     *
     * @param stuPsw the value for studentspass.STU_PSW
     *
     * @mbggenerated Thu Nov 02 22:41:21 CST 2017
     */
    public void setStuPsw(String stuPsw) {
        this.stuPsw = stuPsw == null ? null : stuPsw.trim();
    }
}